### ISSUE TITLE
Online inverse covariance matrix

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#107]
I believe that the first towards online mixture models is to be able to update the inverse of a covariance matrix online. This isn't trivial, but seems reasonably doable. [This](https://christian-igel.github.io/paper/ACECMUaa1p1CMAfES.pdf) paper is a good read. It applies to the specific case of the CMA-ES algorithm, but it doesn't matter.

**Comment by MaxHalford** [comment]
In the end we're going to go with #71, so updating a covariance matrix online isn't of interest anymore.

**Comment by inesani** [comment]
Hi @MaxHalford, I am highly interested on the online computation of the inverse of the covariance matrix so let me ask for an update on this ;) Are you still planning on adding something like this?  As I can see here the issue was closed but I am asking anyway as I haven't been able to find implementations or, at least, good references (besides the one you provide here). Merci!

**Comment by MaxHalford** [comment]
Hey @inesani :). I closed this because we didn't have any need for it anymore.

It really depends on your use case. In some cases, you might be able to use the [Sherman-Morrison formula](https://www.wikiwand.com/en/Sherman%E2%80%93Morrison_formula), but that isn't a general method. There is also the option to use a [Cholesky decomposition](https://www.wikiwand.com/en/Cholesky_decomposition) as a proxy and update that instead. What exactly do you have in mind?

**Comment by inesani** [comment]
Wow!! thanks for the quick reply :)

What I am trying to do is to calculate the Mahalanobis distance on a stream of data in order to perform anomaly detection based on it. The key point is the calculation of the inverse of the covariance in an online manner.
I have taken a look at what you propose and the Sherman-Morrison formula seems like a good start. When you say that it isn't a general method, to what pre-conditions do you refer ?

**Comment by MaxHalford** [comment]
> What I am trying to do is to calculate the Mahalanobis distance on a stream of data in order to perform anomaly detection based on it.

Interesting!

> When you say that it isn't a general method, to what pre-conditions do you refer ?

Actually I'm just referring to the fact that it applies to the particular case of `A + uv`, which is the sum of a matrix with an outer product. Tell me how if it works out for you :). Also, if ever you need it, here is a `numpy` implementation of the Sherman-Morrison formula:

```py
def sherman_morrison(A_inv, u, v):
    num = A_inv @ np.outer(u, v) @ A_inv
    den = 1 + v @ A_inv @ u
    return A_inv - num / den
```

**Comment by inesani** [comment]
When searching about the sherman-morrison formula, I have come accross this blog: https://markusthill.github.io/math/stats/ml/online-estimation-of-the-inverse-covariance-matrix/ that might be a good start. I am just posting it here in case you reopen this :) I'll take a look at the implementation in numpy and see how to adapt this in Java (fun stuff!). Thanks

**Comment by MaxHalford** [comment]
> fun stuff!

Yes, especially on a Sunday.
