### ISSUE TITLE
[Feature Request] Replace numpy with jax.numpy

### ISSUE THREAD

**Issue by kivo360** [creme-ml/creme#141]
For people that are looking for extremely high speed, I'm gonna recommend the use of JAX as a nice replacement. I just saw pyro do the same thing and thought it was a cool idea to use numpy as a probabilistic library.

**Comment by MaxHalford** [comment]
Hey. We don't use `numpy` very much so I don't think that's really an issue. Furthermore, because we are doing many little computations instead of a few big ones, it's very possible that for us `numpy` is in fact slower than pure Python. I just don't feel it's reasonable to use `jax.numpy` without some proof that it will actually bring a worthwhile speedup.

Thanks for the proposition though!
