### ISSUE TITLE
Implement __repr__ for estimators

### ISSUE THREAD

**Issue by jklaise** [creme-ml/creme#151]
Currently all estimators implement `__str__`: https://github.com/creme-ml/creme/blob/master/creme/base.py#L47

However, writing `repr(estimator)` or writing the estimator into an interactive console will still output the Python standard name and memory address. If `__repr__` is implemented, however, then calling `str(estimator)` will automatically look at `__repr__` if `__str__` is not present, so to achieve this functionality it should be enough to just change the current `__str__` to `__repr__` in the `Estimator` definition.

Unless of course there was a conscious decision not to implement `__repr__` for now?

**Comment by MaxHalford** [comment]
The `__str__` method is important because it is what is used for naming and drawing steps in a `Pipeline`. We could indeed make `__repr__` default to calling `__str__`. However, ideally I think it would be nice if `__repr__` also displayed the class parameters, much like [what scikit-learn does](https://scikit-learn.org/stable/auto_examples/plot_changed_only_pprint_parameter.html). This shouldn't be too hard to implement, and a good place to start is to read the [`base.py`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/base.py) file from scikit-learn.

**Comment by MaxHalford** [comment]
Okay so I've taking a good first stab at this. Here is an example:

```python
>>> from creme import preprocessing
>>> from creme import linear_model

>>> model = preprocessing.StandardScaler() | linear_model.LinearRegression()
>>> model
Pipeline (
    StandardScaler () |
    LinearRegression (
        optimizer=SGD
        loss=Squared
        l2=0.0001
        intercept=0.0
        intercept_lr=0.01
    )
)

>>> print(model)
StandardScaler | LinearRegression
```

Does this look good to you?

**Comment by jklaise** [comment]
I haven't dived deep into all the possible things we could represent in a model, but this looks good to me!
