### ISSUE TITLE
pip install for 0.5.1 and Cython

### ISSUE THREAD

**Issue by kevinsteger** [creme-ml/creme#277]
>`pip3 install creme
Collecting creme
  Using cached https://files.pythonhosted.org/packages/50/99/fcc5b4ebc23fba6c7d9306da7893f0d59d2b8bd56f73afc01485b41dc431/creme-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hi5zbab6/creme/setup.py", line 125, in <module>
        compiler_directives={'language_level': 3}
      File "/tmp/pip-build-hi5zbab6/creme/setup.py", line 20, in cythonize
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'`

**Comment by MaxHalford** [comment]
So we have wheels for `creme`, as you can see [here](https://pypi.org/manage/project/creme/release/0.5.1/). Your error is happening because you're using an architecture for which we haven't built any wheels, which is weird because we cover a lot of architectures. There you need to install Cython before installing creme. 

It's a bit tricky to add Cython as a dependency because of the way setuptools works. I'll look into this some more.

**Comment by kevinsteger** [comment]
The issue is that it was installing on an old box Ubuntu 16.04 Python 3.5.2.  Going to update it and I'm sure it will be fine.

**Comment by MaxHalford** [comment]
Cool! Also note that currently `creme` is only tested against Python 3.6, 3.7, and 3.8.
