### ISSUE TITLE
Handling null case of feature?

### ISSUE THREAD

**Issue by deklanw** [creme-ml/creme#301]
Say I have a numeric feature which occasionally is `None`. How do I handle this case with Creme? Does it vary by the model I'm using?

**Comment by MaxHalford** [comment]
We have an [`impute` module](https://creme-ml.github.io/content/api.html#impute-missing-data-imputation) which is supposed to take care of missing values. I've actually refactored it for the next release, stay tuned.

**Comment by deklanw** [comment]
I see. That's good news.

Although, I'm confused about why it's necessary to impute values for `None`, but online one hot encoding works.

How can a model adapt to changing numbers of features via increasing number of possibilities in a categorical feature? (But can't adapt to possibly missing feats?)

**Comment by MaxHalford** [comment]
Online models can adapt to a variable number of features because that's just the way they are designed. It doesn't mean they will perform optimally, but at least they will work and will perform to the best of their ability instead of bugging out and telling you that a feature is missing or that they are too many features. A model can't process a `None` value simply because it isn't a number. Some algorithms, such as naive Bayes models which are inherently discrete, may be able to process `None`s though. We just use `None` as a convention to represent missing values.

**Comment by deklanw** [comment]
Makes sense, thanks
