### ISSUE TITLE
More accurate estimators' __str__ representation

### ISSUE THREAD

**Issue by gbolmier** [creme-ml/creme#82]
When we create a Pipeline or a TransformerUnion on the way, if the same kind of estimator is used along, it's going to result with multiple name conflicts. For instance:

```python
from creme import compose
from creme import feature_extraction
from creme import linear_model
from creme import preprocessing


text_part = compose.Whitelister('text') | feature_extraction.TFIDFVectorizer('text')
num_part = compose.Whitelister(['a']) | feature_extraction.Differ('a')

model = text_part + num_part
model |= preprocessing.StandardScaler()
model |= linear_model.LinearRegression()
```

Here, Whitelister estimator is used twice without being assigned unique names. Therefor, if we want to draw our model for instance, it will result with a merged representation instead of two different nodes. It would be nice to infer explicit names in that case (e.g. with an `infer_name` attribute instead of using `str(estimator)`) and also let the possibility to the user to set names by himself thanks to a `name` parameter when he instantiates an estimator.

Let me know what's your opinion about this. I can take care of it if we validate it :)

**Comment by MaxHalford** [comment]
I know exactly what you mean. I think that the "good" solution is to enforce that the `__str__` representation of each estimator should be accurate. For example `str(Whitelister(['a', 'b']))` should be `Whitelister(['a', 'b'])` or even just `('a', 'b')`, instead of just `Whitelister` as it is now.

If you look at the base class `Estimator` in `base.py`, the default `__str__` method is:

```python
def __str__(self):
        return self.__class__.__name__
```

I think we should just make sure that the string representations are better and look good in a pipeline diagram. I hope I'm being clear.

**Comment by gbolmier** [comment]
Agree with you! Simpler and more effective, I modify the issue title in consequence

**Comment by MaxHalford** [comment]
I'm closing as it's an ongoing thing. It's a good thing the issue was raised!
